# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/elasticsearch/all/elasticsearch.rbi
#
# elasticsearch-7.2.0
module Elasticsearch
end
module Elasticsearch::Transport
end
class Elasticsearch::Transport::Client
  include Elasticsearch::API
  include Elasticsearch::API::Common
end
