# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/powerpack/all/powerpack.rbi
#
# powerpack-0.1.2
module Powerpack
end
module Enumerable
  def average(default = nil); end
  def drop_last(n); end
  def drop_last_while; end
  def exactly?(n); end
  def frequencies; end
  def several?; end
  def take_last(n); end
  def take_last_while; end
end
class Hash
  def symbolize_keys; end
end
class Numeric
  def billion; end
  def hundred; end
  def million; end
  def neg?; end
  def pos?; end
  def quadrillion; end
  def thousand; end
  def trillion; end
end
class String
  def ascii_only!; end
  def ascii_only; end
  def blank?; end
  def format(*args); end
  def remove!(pattern); end
  def remove(pattern); end
  def remove_prefix!(pattern); end
  def remove_prefix(pattern); end
  def remove_suffix!(pattern); end
  def remove_suffix(pattern); end
  def squish!; end
  def squish; end
  def strip_indent; end
  def strip_margin(margin_characters); end
end
class Array
  def butfirst; end
  def butlast; end
end
