apiVersion: v1
kind: Service
metadata:
    name: "opensearch"
spec:
  ports:
    - name: "api"
      port: 9200
      targetPort: 9200
    - name: "performance"
      port: 9600
      targetPort: 9600
  selector:
    app: opensearch
  type: LoadBalancer
status:
  loadBalancer: {}
